project:
  type: website  # Keep it as a website to enable a single-page format
  output-dir: docs

website:
  title: "Population Estimates and Projections for the World Bank"
  site-url: "https://wb-decis.github.io/population-note/"
  repo-url: "https://github.com/WB-DECIS/population-note"
  repo-actions: [source, issue]  
  sidebar:
    logo: "https://datatopics.worldbank.org/world-development-indicators/img/logo-wb-header-en.svg"
    search: true
    tools:
      - text: "Download PDF"
      
format:
  html:
    theme: cosmo
    css: custom.css
    toc: true
    toc-location: right  # Ensures the TOC appears on the right side
    toc-depth: 2  # Controls how many levels of headings appear in TOC
    number-sections: true
    toc-expand: true
    
pdf:
    documentclass: scrreprt  # Uses a structured LaTeX class
    toc: true
    number-sections: true
    papersize: a4
    fontsize: 11pt
    
    