---
title: "Population Estimates and Projections for the World Bank"
subtitle: "Technical note"
# author: "World Bank"
date: "12/23/2024"
format:
  html:
    toc: true
    toc-location: left
    toc-depth: 2
    number-sections: true

website:
  title: "Choosing World Development Indicators"
  site-url: "https://wb-decis.github.io/wdi-indicator-selection/"
  sidebar:
    background: "#fafafa"
    logo: "https://datatopics.worldbank.org/world-development-indicators/img/logo-wb-header-en.svg"
    search: true
    collapse-level: 1  # Controls which levels are collapsed initially
    
---

<script>
  document.addEventListener("DOMContentLoaded", function() {
    var searchBox = document.querySelector("#quarto-search");
    if (searchBox) {
      var textDiv = document.createElement("div");
      textDiv.innerHTML = `
        <div id="sidebar-download">
          <a href="https://datatopics.worldbank.org/world-development-indicators/release-note/publications/Population_Estimates_and_Projections_for_the_World_Bank.pdf" target="_blank">
            <i class="bi bi-file-earmark-pdf"></i> Download PDF
          </a>
        </div>
      `;
      textDiv.style.marginTop = "10px";
      searchBox.parentNode.insertBefore(textDiv, searchBox.nextSibling);
    }
  });
</script>

# Introduction {.unnumbered}

This technical note describes the methodology implemented by the World
Bank to generate population estimates and projections that are reported
in the [World Development Indicators (WDI)
database](https://databank.worldbank.org/source/world-development-indicators)
and the [Population Estimates and Projections
database](https://databank.worldbank.org/reports.aspx?source=health-nutrition-and-population-statistics:-population-estimates-and-projections).
The next page summarizes the four steps of the methodology. The summary
is followed by four sections that elaborate on each step.

Please cite the technical note as follows:

World Bank. 2024. “Population Estimates and Projections for the World
Bank: Technical Note.” Edition December 2024. Available at
<https://datanalytics.worldbank.org/Population-Technical-Note/>

[*This note was prepared by Emi Suzuki, Umar Serajuddin and Daniel Gerszon Mahler of the
World Bank.*]{.smallcaps}

# Non-technical summary {.unnumbered}

### [Section 1](#background): Background {.unnumbered}

The World Bank publishes annual mid-year [population](#population) estimates and projections for over 200 economies from the year 1960 onwards in the [World Development Indicators (WDI) database](https://databank.worldbank.org/source/world-development-indicators) (estimates only) and in the [Population Estimates and Projections database](https://databank.worldbank.org/reports.aspx?source=health-nutrition-and-population-statistics:-population-estimates-and-projections) (estimates and projections, the latter up to the year 2050) [biannually](#frequency).

### [Section 2](#sourceselection): Source of data and selection criteria {.unnumbered}

The main [sources](#sources) of the total population estimates are (1) World Population Prospects (UN WPP), produced by the Population Division (UNPD) of the United Nations Department of Economic and Social Affairs, and (2) national statistical offices (NSOs). For NSOs, the World Bank collects data directly from their publications/databases or through Eurostat’s database. A set of [criteria](#criteria) were developed to determine whether estimates from NSOs or UN WPP would be used for an economy. For NSO population estimates to be used, they must be deemed sufficiently reliable, available as an annual time-series, and reasonably consistent with the World Bank’s definition of population and an economy’s territory.

### [Section 3](#adjustment): Adjustments to acquired data and calculations {.unnumbered}

In cases where the WDI uses NSO estimates, if there are missing data, a short extrapolation of six months or one year is applied when data are missing for the latest year, and UN WPP estimates are used when data are missing for early years. [Adjustments are made to NSO estimates](#NSO) in cases where the reference time of the NSO estimates is different from the mid-year. If NSO estimates are for beginning-of year (or end-of-year), mid-year population is calculated as the arithmetic mean of two beginning-of year (or end-of-year) estimates. Adjustments are also made to the population estimates used only for [GNI/GDP per capita calculations](#GNI) in cases where the geographical coverage of total GNI/GDP data is different from the geographical coverage of the population estimates. For the [population estimates by age, sex and urban/rural](#disaggregate), the proportions from UN WPP (for age and sex) and UNPD’s [World Urbanization Prospects](https://population.un.org/wup/) (UN WUP) (for urban/rural) are taken and multiplied by the WDI’s total population. The total population and population by age, sex, and urban/rural are calculated for the [income/regional groups](#aggregate) by summing up economy-level data.

### [Section 4](#projections): Projections {.unnumbered}

For population projections, medium scenario [projections of UN WPP](#wppprojections) are directly used for the economies where the World Bank uses UN WPP estimates. The [Spectrum software](https://www.avenirhealth.org/software-spectrum.php) is used to generate [projections for the economies where NSO (and Eurostat) estimates are used](%7B#nsoprojections%7D).

# Background {#background}

This section briefly describes the population estimates in the WDI database.

## Population {#population}

Population refers to the total number of alive people in a specific area, such as an economy. It can also refer to the number of people in a specific age group, or by sex. Population are also defined by a reference time period. For annual population estimates, the most commonly used reference times include the beginning of the year (January 1st), the mid-year (July 1st or June 30th), or the end of the year (December 31st). Annual population estimates can also be defined as the average number of people in an area over the year, which is typically close to the mid-year population estimate.

Population censuses, the official counting of population within the territory of an economy, play a critical role in producing population estimates. Most economies conduct a population census at least once every ten years. Typically, population estimates after a census (postcensal estimates) are calculated by using the population data from the census as a base, and then by adding births, subtracting deaths, and adding net migration using empirical data. In the calculation, the census data should be adjusted for coverage error such as under- (or over-) counts, as well as for a reference time of the year. When a subsequent census is conducted, intercensal estimates can be produced by adjusting the postcensal estimates.

As opposed to the population estimates, population projections are calculated by using future assumptions of births, deaths, and migration subsequent to the latest year of estimates.

## WDI’s population estimates

The World Bank publishes annual mid-year population estimates and projections for over 200 economies from the year 1960 in the [World Development Indicators (WDI) database](https://databank.worldbank.org/source/world-development-indicators) (estimates only) and the [Population Estimates and Projections database](https://databank.worldbank.org/reports.aspx?source=health-nutrition-and-population-statistics:-population-estimates-and-projections) (both estimates and projections, the latter up to the year 2050) biannually.

These population estimates serve as the denominator for many per capita measures calculated and published by the World Bank, including per capita GNI estimates that are used as one of the determinants of the Bank’s lending rates and credit terms for economy operations. The population estimates and projections are also used to calculate World Bank’s poverty estimates, such as the number of people living in poverty. In addition, they are used to produce population weighted averages for regions and income groups.

## Frequency of updates {#frequency}

Typically, the population estimates in the WDI database are updated twice a year. Every year on July 1st, population time-series estimates from 1960 to the previous calendar year are published, and the estimates are updated again in mid-December. In each release, the population estimates are prepared by Development Data Group (DECDG), and reviewed and cleared by country economists of the World Bank through the Operational Guidelines exercise (Spring Survey) in March-May for the July 1st release, and through the Fall Survey in September-November for the December release. The Spring Survey and the Fall Survey are annual data collection and review exercises covering national accounts data for borrower economies with World Bank’s country economists.

# Source of data and selection criteria {#sourceselection}

This section describes data sources of the population estimates in the WDI along with the selection criteria of the data sources.

## Data sources {#sources}

The main sources of the total population estimates are (1) [World Population Prospects](https://population.un.org/wpp/) (UN WPP), produced by the Population Division (UNPD) of the [United Nations Department of Economic and Social Affairs](https://www.un.org/development/desa/pd/), and (2) national statistical offices (NSOs). For NSOs, the World Bank collects data directly from their publications/databases or through [Eurostat’s database](https://ec.europa.eu/eurostat/data/database?node_code=earn_ses_monthly). The data source information of each economy is included in country-series metadata in the WDI database and the Population Estimates and Projections database.

## Selection criteria {#criteria}

For NSO population estimates to be used, they must be deemed sufficiently reliable, available as an annal time-series and reasonably consistent with the World Bank’s definition of population and an economy’s territory. A set of criteria was developed on how to determine whether NSO estimates (including Eurostat) or the UN WPP estimates are used. The purpose of developing these criteria is to be guided by data quality when deciding the population source, while being transparent and objective.

1.  **Reliability**: Reliability is measured by:
    1.  Births are registered from civil registration, which is estimated to be at least 90% complete, or from another source, which is estimated to be reliable by the UNSD. Events may be counted when registered, not when they occurred.
    2.  Deaths are registered from civil registration, which is estimated to be at least 90% complete, or from another source which is estimated to be reliable by the UNSD. Events may be counted when registered, not when they occurred.
    3.  Statistics of births, deaths, and migration are applied for time adjustments, or population estimates are sourced annually from a population register.
    4.  A census has been conducted in the past 15 years, or population figures are compiled from administrative registers.
2.  **Availability**: NSO’s estimates must be available in annual time series. Note that NSO’s figures must be estimates, not projections. Estimates are based on a baseline population and empirical data on subsequent births, deaths, and migration, while projections are based on a baseline population and future assumptions of births, deaths, and migration. NSO’s annual time series estimates are used as available, supplemented by UNPD in case for earlier years for which NSO’s annual time series estimates are not available.
3.  **Definition of population**: The NSO uses a definition of population that is reasonably consistent with World Bank’s de-facto definition. For example, population estimates should not include nationals who reside outside of the economy.
4.  **Definition of territory**: Exceptions can be made to the criteria in case the World Bank uses a different territorial definition than the UNPD’s territorial definition; and vice versa.

The reliability criteria 1.1-1.3 use UN Statistics Division’s [Population and Vital Statistics Report](https://unstats.un.org/unsd/demographic-social/products/vitstats/index.cshtml), and the [Demographic Yearbook Metadata](https://unstats.un.org/unsd/demographic-social/products/dyb/#metadata) as the source, while the reliability criterion 1.4 uses the World Bank’s [Statistical Performance Indicators](https://www.worldbank.org/en/programs/statistical-performance-indicators). Two World Bank economies do not figure in the UNSD database: Kosovo and Taiwan. For these economies, the information is gathered from NSO publications. Data for Virgin Islands (U.S.) and Puerto Rico are published by US Census Bureau so the data of the United States are used.

NSO estimates (including Eurostat) are used when they meet all these criteria, which is roughly one third of all economies in the WDI database. The UN WPP estimates are used for the rest.

# Adjustments to acquired data and calculations {#adjustment}

This section describes which data are acquired from the data sources and any adjustments that are applied for reference time and missing data, as well as additional adjustments and more calculations.

##	UN WPP {#WPP}
###	 Use July 1 population estimates from the UN WPP

The data source of total population for roughly two thirds of all economies in the WDI database is UNPD’s [World Population Prospects](https://population.un.org/wpp/) (UN WPP). The UNPD produces population estimates and projections typically every other year. The UN WPP covers years ranging from 1950 to 2100, and the most recent revision of WPP, which was published in July 2024 (WPP 2024 Revision), contains estimates of population and other demographic indicators for 1950-2023, and projections of them for 2024-2100 for 237 economies ([United Nations 2024a](https://population.un.org/wpp/Download/Standard/MostUsed/)). The UN WPP 2024 Revision has annual total population for beginning of year (January 1st) as well as for mid-year (July 1st), and the latter is used as is for the WDI database. Mid-year population is typically more appropriate for representing population figures for the whole year, and also to calculate annual per capita figures such as GDP per capita and GNI per capita as well as other rates, rather than January 1st population.

If the WDI needs a population estimate beyond the latest estimates covered by the UN WPP, medium scenario projections of the UN WPP are used. For example, if the WDI needs population estimates for 2024 for its July 2025 release, but the latest WPP estimates are for 2023, then the WPP projections for 2024 are used. 

The UN WPP takes into account the latest data available, such as censuses, official estimates, demographic surveys, vital event registries, population registries, and other relevant data from NSOs. The UN WPP population estimates are constructed using a cohort-component method, which takes into account the three components of population change -- births, deaths and migration -- to project the population forward in time ([Leslie, 1945](https://doi.org/10.2307/2332297); [Preston et al., 2001](https://link.springer.com/article/10.1023/A:1012569213642); [United Nations 2024b](https://population.un.org/wpp/Publications/Files/WPP2024_Methodology.pdf)). The estimates for each component are taken from relevant data sources and adjusted for under- (or over-) reporting and under- (or over-) enumeration as needed. 

Virtually all censuses have issues of under- (or over) counts. Ideally, after a census, an economy should conduct a post enumeration survey (PES) to measure the magnitude of under- (or over) counts. Economies can make adjustments subsequently. However, many economies often publish census figures without PES and/or without making such adjustments. Under-count is much more common than over-count because missing people during censuses is much more likely to happen than double-counting people ([United Nations 2017](https://unstats.un.org/unsd/publication/SeriesM/Series_M67Rev3en.pdf)). Therefore, such census figures are likely to be under-estimated. The UNPD carries out an analysis that takes into account those issues and seeks to establish past population trends by resolving the inconsistencies ([Pelletier 2020](https://www.un.org/development/desa/pd/sites/www.un.org.development.desa.pd/files/files/documents/2020/Oct/undesa_pd_tp_2020_tp_population_estimates.pdf), [United Nations 2024b](https://population.un.org/wpp/Publications/Files/WPP2024_Methodology.pdf)).

As a result of these adjustments and its methodology, the UN WPP estimates differ from population estimates and census estimates of national statistical offices. These adjustments made in the UN WPP estimates are deemed to reduce potential biases and errors, especially for many low- and middle-income economies, and thus the WDI relies on the UN WPP as the primary source for population estimates for many low- and middle-income economies. 
 
Mid-year population estimates of UN WPP are directly used in the WDI database with one exception: adjustments are made to UN WPP data for WDI’s Channel Islands, for which UN WPP estimates of Guernsey and Jersey are summed up.

##	Eurostat {#Eurostat}
###	 Use average population as they are

The other main data source of population estimates in the WDI is NSOs, where the data is collected directly from NSO publications/databases, or through [Eurostat](https://ec.europa.eu/eurostat/data/database?node_code=earn_ses_monthly). Eurostat collects population and other demographic data from NSOs for European Union (EU) member states as well as from select non-EU European states. For those economies that meet the WDI selection criteria and for which the Eurostat collects data regularly, the [average population in Eurostat database](https://ec.europa.eu/eurostat/databrowser/view/demo_gind/default/table?lang=en&category=demo.demo_ind) are used as they are, where the average population is calculated as [the arithmetic mean of the population on January 1st of two consecutive years](https://ec.europa.eu/eurostat/cache/metadata/en/demo_gind_esms.htm) ([Eurostat 2024](https://ec.europa.eu/eurostat/cache/metadata/en/demo_gind_esms.htm#relatedmd1723209127035)). If there are footnotes in Eurostat’s database indicating notes such as provisional data or break in time series, they are included in the WDI footnotes as well.

###	 Missing data

Although the Eurostat database publishes population data from 1960, some economies have missing data for early years such as before 1980s or 1990s. In this case, for missing years, data are taken from NSOs, and used if available. Otherwise, mid-year population data from UN WPP are used. 

For the latest year, Eurostat publishes average population data around the summer of the subsequent year. Therefore, when mid-year population data are needed for the Operational Guidelines exercise around March, the mid-year/average population data for the latest year needed are not available in Eurostat database. Thus, mid-year (or average) population data are sought from NSO websites of each economy and used if available. If they are not available in the NSO websites, a short extrapolation using the exponential growth rate in the past 6 months is applied to generate a population figure for the latest year temporarily in the July update. The growth rates are calculated from the two most recent data points available in the Eurostat database. The extrapolated figures are replaced with newly available Eurostat data in the subsequent WDI population update cycle.

##	National Statistical Offices (NSOs) {#NSO}
###	 Use mid-year population or average population as they are

In addition to the Eurostat economies, for the economies that meet the WDI selection criteria, NSO population data are directly used for the WDI. Links to official NSO websites are available on the [UN Statistics Division’s website](https://unstats.un.org/home/nso_sites/). NSOs’ population data in time series are searched on the official NSO websites in its databases and publications. If the NSO publishes mid-year (July 1st or June 30th) or average population estimates, the data are taken directly. NSOs often revise/update population estimates, not only for the latest year but also in recent past years. If so, the WDI population estimates are also revised/updated accordingly. If there are footnotes in the NSOs’ database or publications which indicate data are preliminary or there is a break in time series, these notes are included in the WDI footnotes as well.

###	 Adjustments for reference time of the year

Some NSOs publish only end-year (or beginning-of year) population estimates. If this is the case, approximation of mid-year estimates is calculated as the arithmetic mean of the end-year (or beginning-of year) estimates of two consecutive years.

###	 Missing data

Some of the NSOs do not publish time-series population estimates for early years. The missing years range from 1960s to 2000s, depending on the economy. In this case, mid-year population data from UN WPP are used for the missing years.

If population data for the latest year(s) are not yet available from the NSO, a short extrapolation (typically 1 year or 6 months) is applied using an exponential growth rate to generate a population figure for the latest year(s) temporarily. The exponential growth rates are calculated from the two most recent population data points available from the NSO. The extrapolated figures are replaced with newly available NSO data in the subsequent WDI population update cycle.

## Adjustments of geographical areas to six economies only for GNI/GDP per capita calculation {#GNI}

There are 6 economies (Cyprus, Morocco, Russian Federation, Sudan, Tanzania, Ukraine) for which estimates for total GNI/GDP data and WDI population data cover different geographic areas for part or the entire period since 1960. Adjusted population estimates are calculated separately for the six economies and used only for GNI/GDP per capita calculations to be consistent with the geographic coverage of the numerator -- total GNI and total GDP (see table below). These adjusted population estimates are not published in the WDI, as only the original population estimates are published in the WDI.

| Economy            | WDI Population coverage  | Geographical coverage of GDP/GNI data                                  | Adjustments to population for GDP/GNI per capita calculation                                                                                                                                                                                                                                                                                                                                                              |
|------------------|------------------|------------------|------------------|
| Cyprus             | Includes northern Cyprus | Area controlled by the government of Cyprus (excludes northern Cyprus) | Eurostat average population is used, which covers only government-controlled area.                                                                                                                                                                                                                                                                                                                                        |
| Morocco            | For Morocco only         | For Morocco and Western Sahara                                         | UN WPP data for Morocco and Western Sahara are added.                                                                                                                                                                                                                                                                                                                                                                     |
| Russian Federation | Excludes Crimea          | Includes Crimea (2014 onwards)                                         | NSO data are used which includes Crimea from 2014 onwards.                                                                                                                                                                                                                                                                                                                                                                |
| Serbia             | Excludes South Sudan     | Includes South Sudan (up to mid-2011)                                  | UN WPP data, which has population data for Sudan and South Sudan separately for the entire time series, are added from 1960 to mid-2011.                                                                                                                                                                                                                                                                                  |
| Tanzania           | Includes Zanzibar        | Mainland Tanzania (excludes Zanzibar)                                  | Proportion of population in Zanzibar of total population is calculatedfrom 1978, 1988, 2002, 2012, 2022 censuses and applied to UN WPP data which includes Zanzibar. Constant rate of change is assumed between the censuses, and the same constant rate of change as the one between 2012 and 2022 censuses is assumed after the 2022 census. Before the 1978 census, the same proportion as the 1978 census is assumed. |
| Ukraine            | Includes Crimea          | Excludes Crimea (2014 onwards)                                         | Population data for Crimea from the Russian NSO are used to subtract Crimea’s population from 2014 onwards from the UN WPP population which includes Crimea.                                                                                                                                                                                                                                                              |

:  **Economies with population adjustments for GNI/GDP per capita calculation purposes**

## Population by age, sex, urban/rural {#disaggregate} 

The WDI database also covers population proportions and numbers by age, sex, and urban/rural. The proportions by age and sex are taken from the UN WPP, and proportions by urban/rural are taken from UNPD’s [World Urbanization Prospects](https://population.un.org/wup/) (UN WUP). To calculate population numbers by age, sex, and urban/rural, the proportions from the UN WPP or UN WUP are multiplied by the WDI total population estimates.

## Aggregates by income and regional groups {#aggregate}

Economies in the WDI are grouped by income, regional and other groups. The sum of the total population or numbers by age, sex, urban/rural are calculated for the income and regional groups, by summing up the specified population of the economies in the group. Averages of proportion for the income/regional groups are calculated by using population weighted averages.

# Projections {#projections}

This section describes the coverage, sources, methodology and timeline of the projections in the Population estimates and projections database.

##	Population projections {#popprojections}


In addition to the population estimates, the World Bank also publishes population projections. Population projections give a picture of hypothetical population size and structure in the future that are based on a set of assumptions for future levels and patterns of fertility, mortality and migration. Typically, the population by age and sex of the most recent year is used as a baseline population, and assumptions are made on future levels and patterns of fertility, mortality, and migration based on estimates of the most recent year and past trends leading up to the most recent year. 

The UN WPP 2024 Revision published population projections for 2024-2100, including several scenarios with different fertility assumptions. The medium scenario is most used. The medium scenario projection corresponds to the mean fertility and mortality and median net migration of several thousand distinct trajectories of each demographic component derived using a probabilistic model of the variability in changes over time ([United Nations 2024](https://population.un.org/wpp/Publications/Files/WPP2024_Methodology.pdf)). The [Population estimates and projections database](https://databank.worldbank.org/source/health-nutrition-and-population-statistics:-population-estimates-and-projections) publishes both population estimates and projections up to 2050, while the WDI database publishes population estimates only.

##	Economies that use UN WPP estimates  {#wppprojections}


For the economies that use UN WPP estimates for the latest year (which is the baseline population for projections), the UN WPP medium scenario projections for mid-year are directly used for the World Bank projections.

##	Economies that use NSO or Eurostat estimates {#nsoprojections}


For the economies that use NSO or Eurostat estimates for the latest year, projections are generated using [Spectrum software](https://www.avenirhealth.org/software-spectrum.php). Baseline populations and future assumptions on fertility, mortality and migration from UN WPP estimates and medium variant projections are pre-populated into Spectrum, and they are changeable by the user. When generating population projections through Spectrum, only the pre-populated baseline population is replaced with the WDI population by age/sex of the year, and pre-populated future assumptions on fertility, mortality and migration from UN WPP are used as they are. When projections are generated, only the projected total population is taken from Spectrum projection. Future populations by age, sex, urban/rural are then calculated by multiplying the projected total population by the proportions from the UN WPP medium projection or UN WUP.

##	Frequency of updates

Population projections are generated once the WDI population estimates are finalized internally through the Operational Guidelines exercise or the Fall Survey. The population projections are updated and released biannually at the same time as the WDI population releases that are around July 1st and mid-December. 

